mysql:
  ip: localhost
  port: 3306
  user: root
  password: hsp
  database: db1

redis:
  redisAddr: 10.151.1.122:6379
  password:
  redisDB:

rabbitmq:
  rabbitMQ: amqp
  rabbitMQUser: guest
  rabbitMQPassWord: guest
  rabbitMQHost: 10.151.1.122
  rabbitMQPort: 5672
